name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: '0 0 * * *' # Daily run at midnight UTC

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run Regular Tests
        id: regular-tests
        continue-on-error: true
        run: |
          echo "Debug - First 2 chars of username: ${TEST_USER_USERNAME:0:2}***"
          echo "Debug - Password length: ${#TEST_USER_PASSWORD}"
          for i in {1..3}; do
            echo "Attempt $i of 3"
            if npm run test:ci; then
              exit 0
            fi
            sleep 10
          done
          exit 1
        env:
          CI: true
          TEST_USER_USERNAME: ${{ secrets.PARABANK_USERNAME }}
          TEST_USER_PASSWORD: ${{ secrets.PARABANK_PASSWORD }}
          HEADLESS: true

      # Run E2E tests only on scheduled runs or manual triggers
      - name: Run E2E Tests
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        id: e2e-tests
        continue-on-error: true
        run: |
          echo "Running full E2E test suite..."
          npm run test:e2e
        env:
          CI: true
          TEST_USER_USERNAME: ${{ secrets.PARABANK_USERNAME }}
          TEST_USER_PASSWORD: ${{ secrets.PARABANK_PASSWORD }}
          HEADLESS: true

      - name: Run API Tests
        id: api-tests
        continue-on-error: true
        run: |
          for i in {1..3}; do
            echo "Attempt $i of 3"
            if npm run test:api; then
              exit 0
            fi
            sleep 10
          done
          exit 1
        env:
          CI: true
          TEST_USER_USERNAME: ${{ secrets.PARABANK_USERNAME }}
          TEST_USER_PASSWORD: ${{ secrets.PARABANK_PASSWORD }}
          HEADLESS: true

      - name: Process Test Results
        id: test-results
        run: |
          if [[ "${{ steps.regular-tests.outcome }}" == 'failure' || "${{ steps.api-tests.outcome }}" == 'failure' ]]; then
            echo "Regular tests failed after retries"
            exit 1
          fi

          if [[ "${{ github.event_name }}" == 'schedule' || "${{ github.event_name }}" == 'workflow_dispatch' ]]; then
            if [[ "${{ steps.e2e-tests.outcome }}" == 'failure' ]]; then
              echo "E2E tests failed"
              exit 1
            fi
          fi

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ github.run_number }}
          path: |
            playwright-report/
            test-results/
          retention-days: 30
